#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
IOCParser command-line launcher script

Author: Marc Rivero | @seifreed
"""

from iocparser.main import main

if __name__ == "__main__":
    main() 