apiVersion: v1
kind: Secret
metadata:
  name: iocparser-worker-secrets
type: Opaque
stringData:
  IOCPARSER_WORKER_QUEUE_URL: "amqp://user:password@rabbitmq.default.svc.cluster.local:5672/"
  IOCPARSER_WORKER_DB_URI: "mysql+pymysql://user:password@mariadb.default.svc.cluster.local:3306/iocparser"
