from __future__ import annotations

from pathlib import Path

import pytest

from iocparser.application.contracts import (
    ExtractFileInput,
    ExtractTextInput,
    ExtractURLInput,
    PersistRunInput,
)
from iocparser.application.use_cases import (
    extract_from_file,
    extract_from_files,
    extract_from_text,
    extract_from_url,
    persist_run,
)
from iocparser.domain.models import (
    IOC,
    ExtractionOptions,
    ExtractionResult,
    PersistOptions,
    Source,
    WarningMatch,
)
from iocparser.errors import FileSizeError, SourceNotFoundError, SourceProcessingError
from iocparser.infrastructure.extraction import DefaultIOCExtractionEngine
from iocparser.infrastructure.file_batch_executor import ThreadPoolFileBatchExecutor
from iocparser.infrastructure.temp_files import TemporaryFileCleaner


class RecordingWarningService:
    def __init__(self) -> None:
        self.force_update_values: list[bool] = []
        self.last_iocs: tuple[IOC, ...] = ()

    def separate(self, iocs: tuple[IOC, ...], *, force_update: bool = False) -> ExtractionResult:
        self.last_iocs = iocs
        self.force_update_values.append(force_update)
        return ExtractionResult(
            iocs=(),
            warnings=(
                WarningMatch(
                    ioc=iocs[0],
                    warning_list="Known Good",
                    description="Generated by test",
                ),
            ),
        )


class MappingReader:
    def __init__(self, mapping: dict[str, str | Exception]) -> None:
        self.mapping = mapping

    def read(self, source_path: str, options: ExtractionOptions) -> str:
        del options
        value = self.mapping[source_path]
        if isinstance(value, Exception):
            raise value
        return value


class PassThroughDownloader:
    def __init__(self, path: str) -> None:
        self.path = path

    def download(self, url: str) -> str:
        del url
        return self.path


class LenientReader:
    def read(self, source_path: str, options: ExtractionOptions) -> str:
        del source_path, options
        return "IOC URL: https://kept.example/path"


class RecordingSourceRepository:
    def __init__(self) -> None:
        self.calls: list[dict[str, object]] = []

    def get_or_create(self, **kwargs: object) -> int:
        self.calls.append(kwargs)
        return 7


class RecordingIOCRepository:
    def __init__(self) -> None:
        self.normal_calls: list[ExtractionResult] = []
        self.warning_calls: list[ExtractionResult] = []

    def get_or_create_normal(self, result: ExtractionResult) -> list[int]:
        self.normal_calls.append(result)
        return [11, 12]

    def get_or_create_warnings(self, result: ExtractionResult) -> list[int]:
        self.warning_calls.append(result)
        return [21]


class RecordingRunRepository:
    def __init__(self, *, fail_on_create: bool = False) -> None:
        self.fail_on_create = fail_on_create
        self.create_calls: list[tuple[int, str, PersistOptions]] = []
        self.attach_calls: list[tuple[int, list[int]]] = []

    def create_run(
        self,
        *,
        source_id: int,
        tool_version: str,
        options: PersistOptions,
        metadata: dict[str, int] | None = None,
    ) -> int:
        del metadata
        self.create_calls.append((source_id, tool_version, options))
        if self.fail_on_create:
            raise RuntimeError("boom")
        return 99

    def attach_iocs(
        self, *, run_id: int, ioc_ids: list[int], result: ExtractionResult | None = None
    ) -> None:
        del result
        self.attach_calls.append((run_id, ioc_ids))


class RecordingUnitOfWork:
    def __init__(self, *, fail_on_create: bool = False) -> None:
        self.source_repository = RecordingSourceRepository()
        self.ioc_repository = RecordingIOCRepository()
        self.run_repository = RecordingRunRepository(fail_on_create=fail_on_create)
        self.committed = False
        self.rolled_back = False

    def commit(self) -> None:
        self.committed = True

    def rollback(self) -> None:
        self.rolled_back = True


def test_extract_from_text_uses_warning_service_when_enabled() -> None:
    warning_service = RecordingWarningService()

    result = extract_from_text(
        ExtractTextInput(
            text_content="IOC domain: Example[.]com",
            options=ExtractionOptions(defang=True, check_warnings=True, force_update=True),
        ),
        extractor_engine=DefaultIOCExtractionEngine(),
        warning_service=warning_service,
    )

    assert result.iocs == ()
    assert len(result.warnings) == 1
    assert warning_service.force_update_values == [True]
    assert warning_service.last_iocs[0].canonical_value() == "example.com"


def test_extract_from_text_skips_warning_service_when_disabled() -> None:
    result = extract_from_text(
        ExtractTextInput(
            text_content="IOC URL: https://plain.example/path",
            options=ExtractionOptions(defang=False, check_warnings=False),
        ),
        extractor_engine=DefaultIOCExtractionEngine(),
    )

    assert result.grouped_iocs() == {"urls": ["https://plain.example/path"]}
    assert result.warnings == ()


def test_extract_from_file_wraps_unexpected_errors() -> None:
    request = ExtractFileInput(
        file_path="/tmp/broken.txt",
        options=ExtractionOptions(file_type="text", check_warnings=False),
    )
    reader = MappingReader({"/tmp/broken.txt": ValueError("bad parser")})

    with pytest.raises(SourceProcessingError):
        extract_from_file(request, reader=reader, extractor_engine=DefaultIOCExtractionEngine())


def test_extract_from_file_preserves_validation_errors() -> None:
    request = ExtractFileInput(
        file_path="/tmp/too-large.txt",
        options=ExtractionOptions(file_type="text", check_warnings=False),
    )
    reader = MappingReader({"/tmp/too-large.txt": FileSizeError(2.0, 1.0)})

    with pytest.raises(FileSizeError):
        extract_from_file(request, reader=reader, extractor_engine=DefaultIOCExtractionEngine())


def test_extract_from_url_reads_and_cleans_up_temp_file(tmp_path: Path) -> None:
    temp_file = tmp_path / "downloaded.txt"
    temp_file.write_text("IOC URL: https://cleanup.example/path", encoding="utf-8")
    downloader = PassThroughDownloader(str(temp_file))
    reader = MappingReader({str(temp_file): temp_file.read_text(encoding="utf-8")})

    result = extract_from_url(
        ExtractURLInput(
            url="https://source.example/doc",
            options=ExtractionOptions(file_type="text", defang=False, check_warnings=False),
        ),
        downloader=downloader,
        reader=reader,
        extractor_engine=DefaultIOCExtractionEngine(),
        temporary_resource_cleaner=TemporaryFileCleaner(),
    )

    assert result.grouped_iocs() == {"urls": ["https://cleanup.example/path"]}
    assert not temp_file.exists()


def test_extract_from_url_ignores_cleanup_errors_for_directories(tmp_path: Path) -> None:
    temp_dir = tmp_path / "downloaded-dir"
    temp_dir.mkdir()
    downloader = PassThroughDownloader(str(temp_dir))

    result = extract_from_url(
        ExtractURLInput(
            url="https://source.example/doc",
            options=ExtractionOptions(file_type="text", defang=False, check_warnings=False),
        ),
        downloader=downloader,
        reader=LenientReader(),
        extractor_engine=DefaultIOCExtractionEngine(),
        temporary_resource_cleaner=TemporaryFileCleaner(),
    )

    assert result.grouped_iocs() == {"urls": ["https://kept.example/path"]}
    assert temp_dir.exists()


def test_extract_from_files_returns_empty_result_for_partial_failures(tmp_path: Path) -> None:
    existing_file = tmp_path / "existing.txt"
    existing_file.write_text("IOC URL: https://ok.example/path", encoding="utf-8")
    missing_file = tmp_path / "missing.txt"
    reader = MappingReader(
        {
            str(existing_file): existing_file.read_text(encoding="utf-8"),
            str(missing_file): SourceNotFoundError(str(missing_file)),
        }
    )

    results = extract_from_files(
        [
            ExtractFileInput(
                str(existing_file),
                ExtractionOptions(file_type="text", defang=False, check_warnings=False),
            ),
            ExtractFileInput(
                str(missing_file),
                ExtractionOptions(file_type="text", defang=False, check_warnings=False),
            ),
        ],
        reader=reader,
        extractor_engine=DefaultIOCExtractionEngine(),
        batch_executor=ThreadPoolFileBatchExecutor(max_workers=1),
    )

    assert results[str(existing_file)].grouped_iocs() == {"urls": ["https://ok.example/path"]}
    assert results[str(missing_file)] == ExtractionResult()


def test_persist_run_commits_on_success() -> None:
    unit_of_work = RecordingUnitOfWork()
    request = PersistRunInput(
        source=Source.from_raw("file", "/tmp/sample.txt"),
        result=ExtractionResult(
            iocs=(IOC.from_raw("domains", "example.com"),),
            warnings=(
                WarningMatch(
                    ioc=IOC.from_raw("ips", "198.51.100.7"),
                    warning_list="Known Good",
                    description="Generated by test",
                ),
            ),
        ),
        tool_version="1.2.3",
        options=PersistOptions(
            defang=True,
            check_warnings=True,
            force_update=False,
            output_format="json",
        ),
    )

    persisted = persist_run(request, unit_of_work=unit_of_work)

    assert persisted.run_id == 99
    assert unit_of_work.committed is True
    assert unit_of_work.rolled_back is False
    assert unit_of_work.source_repository.calls == [
        {
            "kind": "file",
            "value": "/tmp/sample.txt",
            "original_url": None,
            "normalized_url": None,
            "mime_type": None,
            "input_size": None,
            "content_hash": None,
            "fingerprint": None,
        }
    ]
    assert unit_of_work.run_repository.attach_calls == [(99, [11, 12, 21])]


def test_persist_run_rolls_back_on_failure() -> None:
    unit_of_work = RecordingUnitOfWork(fail_on_create=True)
    request = PersistRunInput(
        source=Source.from_raw("url", "https://source.example"),
        result=ExtractionResult(iocs=(IOC.from_raw("domains", "example.com"),)),
        tool_version="1.2.3",
        options=PersistOptions(
            defang=False,
            check_warnings=False,
            force_update=False,
            output_format="text",
        ),
    )

    with pytest.raises(RuntimeError):
        persist_run(request, unit_of_work=unit_of_work)

    assert unit_of_work.committed is False
    assert unit_of_work.rolled_back is True


def test_persist_run_preserves_original_error_when_rollback_fails(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    unit_of_work = RecordingUnitOfWork(fail_on_create=True)

    def _rollback() -> None:
        raise RuntimeError("rollback failed")

    monkeypatch.setattr(unit_of_work, "rollback", _rollback)
    request = PersistRunInput(
        source=Source.from_raw("url", "https://source.example"),
        result=ExtractionResult(iocs=(IOC.from_raw("domains", "example.com"),)),
        tool_version="1.2.3",
        options=PersistOptions(
            defang=False,
            check_warnings=False,
            force_update=False,
            output_format="text",
        ),
    )

    with pytest.raises(RuntimeError, match="boom"):
        persist_run(request, unit_of_work=unit_of_work)
