from typing import Generic, Iterator, TypeVar, overload

T = TypeVar("T")
T1 = TypeVar("T1")
T2 = TypeVar("T2")
T3 = TypeVar("T3")
T4 = TypeVar("T4")


class Engine:
    dialect: Dialect
    def connect(self) -> Connection: ...
    def begin(self) -> Connection: ...
    def dispose(self) -> None: ...


class Connection:
    def __enter__(self) -> Connection: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    def execute(self, statement: ClauseElement, parameters: object = ...) -> Result[object]: ...
    def exec_driver_sql(self, statement: str) -> Result[object]: ...
    def execution_options(self, **kwargs: object) -> Connection: ...
    def commit(self) -> None: ...


class ClauseElement:
    def params(self, **kwargs: object) -> ClauseElement: ...
    def subquery(self) -> ClauseElement: ...
    def __invert__(self) -> ClauseElement: ...


class Executable(ClauseElement):
    ...


class ColumnExpression(ClauseElement, Generic[T]):
    def in_(self, values: object) -> ClauseElement: ...
    def like(self, value: str, *, escape: str | None = None) -> ClauseElement: ...
    def not_like(self, value: str, *, escape: str | None = None) -> ClauseElement: ...
    def desc(self) -> ClauseElement: ...
    def asc(self) -> ClauseElement: ...
    def is_(self, other: object) -> ClauseElement: ...
    def is_not(self, other: object) -> ClauseElement: ...
    def contains(self, other: object) -> ClauseElement: ...
    def __eq__(self, other: object) -> ClauseElement: ...  # type: ignore[override]
    def __ne__(self, other: object) -> ClauseElement: ...  # type: ignore[override]
    def __ge__(self, other: object) -> ClauseElement: ...
    def __gt__(self, other: object) -> ClauseElement: ...
    def __le__(self, other: object) -> ClauseElement: ...
    def __lt__(self, other: object) -> ClauseElement: ...
    def __invert__(self) -> ClauseElement: ...


class Select(Executable, Generic[T]):
    def where(self, *criteria: object) -> Select[T]: ...
    def join(self, *args: object, **kwargs: object) -> Select[T]: ...
    def outerjoin(self, *args: object, **kwargs: object) -> Select[T]: ...
    def order_by(self, *criteria: object) -> Select[T]: ...
    def limit(self, value: int) -> Select[T]: ...
    def offset(self, value: int) -> Select[T]: ...
    def select_from(self, *froms: object) -> Select[T]: ...
    def params(self, **kwargs: object) -> Select[T]: ...
    def with_for_update(self) -> Select[T]: ...
    def execution_options(self, **kwargs: object) -> Select[T]: ...


class Delete(Executable):
    def where(self, *criteria: object) -> Delete: ...


class Result(Generic[T]):
    def all(self) -> list[T]: ...
    def first(self) -> T | None: ...
    def scalar_one(self) -> T: ...
    def scalar_one_or_none(self) -> T | None: ...
    def scalars(self) -> ScalarResult[T]: ...


class ScalarResult(Generic[T]):
    def __iter__(self) -> Iterator[T]: ...
    def all(self) -> list[T]: ...
    def first(self) -> T | None: ...
    def one_or_none(self) -> T | None: ...


class Inspector:
    def get_table_names(self) -> list[str]: ...
    def get_columns(self, table_name: str) -> list[dict[str, object]]: ...


class MetaData:
    def create_all(self, engine: Engine) -> None: ...


class Boolean:
    ...


class DateTime:
    ...


class ForeignKey:
    def __init__(self, target: str) -> None: ...


class Integer:
    ...


class String:
    def __init__(self, length: int | None = None) -> None: ...


class Text:
    ...


class Dialect:
    name: str


class UniqueConstraint:
    def __init__(self, *columns: str, name: str | None = None) -> None: ...


class Index:
    def __init__(self, name: str, *columns: str) -> None: ...


class FunctionNamespace:
    def count(self) -> ColumnExpression[int]: ...
    def lower(self, *args: object) -> ColumnExpression[str]: ...
    def coalesce(self, *args: object) -> ColumnExpression[str]: ...


func: FunctionNamespace


def create_engine(url: str, future: bool = ...) -> Engine: ...


@overload
def select(entity0: type[T], /) -> Select[T]: ...
@overload
def select(entity0: ColumnExpression[T], /) -> Select[T]: ...
@overload
def select(entity0: type[T1], entity1: type[T2], /) -> Select[tuple[T1, T2]]: ...
@overload
def select(entity0: type[T1], entity1: type[T2], entity2: type[T3], /) -> Select[tuple[T1, T2, T3]]: ...
@overload
def select(entity0: type[T1], entity1: type[T2], entity2: type[T3], entity3: type[T4], /) -> Select[tuple[T1, T2, T3, T4]]: ...
@overload
def select(entity0: object, entity1: object, /, *entities: object) -> Select[tuple[object, ...]]: ...


def text(sql: str) -> ClauseElement: ...
def inspect(subject: Engine | Connection) -> Inspector: ...
def and_(*criteria: object) -> ClauseElement: ...
def or_(*criteria: object) -> ClauseElement: ...
def delete(entity: type[object]) -> Delete: ...
def exists(stmt: object = ...) -> ClauseElement: ...
