from typing import Generic, TypeVar

from sqlalchemy import Engine, MetaData, Select

T = TypeVar("T")


class DeclarativeBase:
    metadata: MetaData
    def __init__(self, **kwargs: object) -> None: ...


class Mapped(Generic[T]):
    def __get__(self, instance: object, owner: object | None = ...) -> T: ...
    def __set__(self, instance: object, value: T) -> None: ...
    def __eq__(self, other: object) -> bool: ...


def mapped_column(type_: object, *args: object, **kwargs: object) -> Mapped[T]:
    ...


def relationship(*args: object, **kwargs: object) -> Mapped[T]:
    ...


class Result(Generic[T]):
    def scalar_one_or_none(self) -> T | None: ...


class Session:
    def __init__(self, engine: Engine) -> None: ...
    def __enter__(self) -> "Session": ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    def execute(self, stmt: Select[T]) -> Result[T]: ...
    def add(self, obj: object) -> None: ...
    def flush(self) -> None: ...
    def commit(self) -> None: ...
