from typing import Generic, TypeVar, overload

from sqlalchemy import ColumnExpression, Engine, MetaData, Result, Select

T = TypeVar("T")


class DeclarativeBase:
    metadata: MetaData
    def __init__(self, **kwargs: object) -> None: ...


class RelationshipExpression(ColumnExpression[T], Generic[T]):
    def has(self, **kwargs: object) -> ColumnExpression[bool]: ...


class Mapped(Generic[T]):
    @overload
    def __get__(self, instance: None, owner: object | None = ...) -> ColumnExpression[T]: ...
    @overload
    def __get__(self, instance: object, owner: object | None = ...) -> T: ...
    def __set__(self, instance: object, value: T) -> None: ...


class RelationshipMapped(Mapped[T], Generic[T]):
    @overload
    def __get__(self, instance: None, owner: object | None = ...) -> RelationshipExpression[T]: ...
    @overload
    def __get__(self, instance: object, owner: object | None = ...) -> T: ...


def mapped_column(type_: object, *args: object, **kwargs: object) -> Mapped[T]: ...
def relationship(*args: object, **kwargs: object) -> RelationshipMapped[T]: ...


class SessionTransaction:
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class Session:
    def __init__(self, engine: Engine) -> None: ...
    def __enter__(self) -> Session: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    @overload
    def execute(self, stmt: Select[T]) -> Result[T]: ...
    @overload
    def execute(self, stmt: object) -> Result[object]: ...
    def add(self, obj: object) -> None: ...
    def flush(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def delete(self, obj: object) -> None: ...
    def refresh(self, obj: object) -> None: ...
    def get(self, entity: type[T], ident: object) -> T | None: ...
    def get_bind(self) -> Engine: ...
    def query(self, entity: type[T]) -> Query[T]: ...
    def begin_nested(self) -> SessionTransaction: ...


class Query(Generic[T]):
    def filter(self, *criteria: object) -> Query[T]: ...
    def count(self) -> int: ...
